
  package net.ivoa.dm.adqlgeom.test;

    
    
/**
* Just for testing.
*
* objectType:  ATest
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      

  @jakarta.persistence.Entity
  
  @jakarta.persistence.Table( name = "ATest" ,schema="adqltest" )
  
  @jakarta.persistence.NamedQueries( {
    @jakarta.persistence.NamedQuery( name = "ATest.findById", query = "SELECT o FROM ATest o WHERE o._id = :id")
  
  } )
      

  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "ATest"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NONE )
              
//@jakarta.xml.bind.annotation.XmlRootElement( name = "ATest")
      
@org.ivoa.vodml.annotation.VoDml(id="adqltest:ATest", role=org.ivoa.vodml.annotation.VodmlRole.objectType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="Just for testing")
    

      public  class ATest 
       implements org.ivoa.vodml.jpa.JPAManipulationsForObjectType<Long> {
      
          /**
          * inserted database key
          */
          @jakarta.persistence.Id
          @jakarta.persistence.GeneratedValue
          @jakarta.persistence.Column(name = "ID")
          
              @jakarta.xml.bind.annotation.XmlTransient
              // @com.fasterxml.jackson.annotation.JsonIgnore
          
          protected Long _id = (long) 0;

          /**
          * @return the id
          */
          @Override
          public Long getId() {
          return _id;
          }

          

    /**
    * . : Attribute apoint : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqltest:ATest.apoint", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "apoint", required =true, type = org.javastro.ivoacore.pgsphere.types.Point.class)
            
                  @jakarta.persistence.Embedded
                      
        @jakarta.persistence.AttributeOverrides( {
        @jakarta.persistence.AttributeOverride(name="", column = @jakarta.persistence.Column(name="apoint",nullable = false ))
        })
        
    protected org.javastro.ivoacore.pgsphere.types.Point apoint;
        

    /**
    * . : Attribute acircle : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqltest:ATest.acircle", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Circle",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "acircle", required =true, type = org.ivoa.dm.adqlgeom.Circle.class)
            
                  @jakarta.persistence.Embedded
                      
        @jakarta.persistence.AttributeOverrides( {
        @jakarta.persistence.AttributeOverride(name="center", column = @jakarta.persistence.Column(name="acircle_center",nullable = false )),
@jakarta.persistence.AttributeOverride(name="radius", column = @jakarta.persistence.Column(name="acircle_radius",nullable = false ))
        })
        
    protected org.ivoa.dm.adqlgeom.Circle acircle;
        

    /**
    * . : Attribute apoly : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqltest:ATest.apoly", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Polygon",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "apoly", required =true, type = org.ivoa.dm.adqlgeom.Polygon.class)
            
                  @jakarta.persistence.Embedded
                      
        @jakarta.persistence.AttributeOverrides( {
        @jakarta.persistence.AttributeOverride(name="points", column = @jakarta.persistence.Column(name="apoly_points",nullable = false ))
        })
        
    protected org.ivoa.dm.adqlgeom.Polygon apoly;
        

    /**
    * . : Attribute aninterval : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqltest:ATest.aninterval", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Interval",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "aninterval", required =true, type = org.ivoa.dm.adqlgeom.Interval.class)
            
                  @jakarta.persistence.Embedded
                      
        @jakarta.persistence.AttributeOverrides( {
        @jakarta.persistence.AttributeOverride(name="lower", column = @jakarta.persistence.Column(name="aninterval_lower",nullable = false )),
@jakarta.persistence.AttributeOverride(name="upper", column = @jakarta.persistence.Column(name="aninterval_upper",nullable = false ))
        })
        
    protected org.ivoa.dm.adqlgeom.Interval aninterval;
        

      /**
       * Creates a new ATest
       */
      public ATest() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param apoint .
        *   @param acircle .
        *   @param apoly .
        *   @param aninterval .
        */
        public  ATest (
          final org.javastro.ivoacore.pgsphere.types.Point apoint, final org.ivoa.dm.adqlgeom.Circle acircle, final org.ivoa.dm.adqlgeom.Polygon apoly, final org.ivoa.dm.adqlgeom.Interval aninterval
        )
        {
            super();
           
                       this.apoint = apoint;
                   
                       this.acircle = acircle;
                   
                       this.apoly = apoly;
                   
                       this.aninterval = aninterval;
                   
          }
        

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  ATest ( final ATest other)
        {
        
                super ();
            
                    if (other.apoint != null )this.apoint= new org.javastro.ivoacore.pgsphere.types.Point(other.apoint);
                
                    if (other.acircle != null )this.acircle= new org.ivoa.dm.adqlgeom.Circle(other.acircle);
                
                    if (other.apoly != null )this.apoly= new org.ivoa.dm.adqlgeom.Polygon(other.apoly);
                
                    if (other.aninterval != null )this.aninterval= new org.ivoa.dm.adqlgeom.Interval(other.aninterval);
                

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final ATest other)
        {

        
                    if (other.apoint != null )this.apoint= new org.javastro.ivoacore.pgsphere.types.Point(other.apoint);
                
                    if (other.acircle != null )this.acircle= new org.ivoa.dm.adqlgeom.Circle(other.acircle);
                
                    if (other.apoly != null )this.apoly= new org.ivoa.dm.adqlgeom.Polygon(other.apoly);
                
                    if (other.aninterval != null )this.aninterval= new org.ivoa.dm.adqlgeom.Interval(other.aninterval);
                

        }

        
        /**
        * Returns apoint Attribute.
        * @return apoint Attribute
        */
        
        public org.javastro.ivoacore.pgsphere.types.Point getApoint() {
        return (org.javastro.ivoacore.pgsphere.types.Point)this.apoint;
        }
        
        
        /**
        * Set apoint Attribute.
        * @param pApoint value to set
        */
        public void setApoint(final org.javastro.ivoacore.pgsphere.types.Point pApoint) {
        
        this.apoint = pApoint;
        }
        
        /**
        * fluent setter for apoint Attribute.
        * @param pApoint value to set
        * @return ATest
        */
        public net.ivoa.dm.adqlgeom.test.ATest withApoint(final org.javastro.ivoacore.pgsphere.types.Point pApoint) {
        setApoint(pApoint);
        return this;
        }

    
        /**
        * Returns acircle Attribute.
        * @return acircle Attribute
        */
        
        public org.ivoa.dm.adqlgeom.Circle getAcircle() {
        return (org.ivoa.dm.adqlgeom.Circle)this.acircle;
        }
        
        
        /**
        * Set acircle Attribute.
        * @param pAcircle value to set
        */
        public void setAcircle(final org.ivoa.dm.adqlgeom.Circle pAcircle) {
        
        this.acircle = pAcircle;
        }
        
        /**
        * fluent setter for acircle Attribute.
        * @param pAcircle value to set
        * @return ATest
        */
        public net.ivoa.dm.adqlgeom.test.ATest withAcircle(final org.ivoa.dm.adqlgeom.Circle pAcircle) {
        setAcircle(pAcircle);
        return this;
        }

    
        /**
        * Returns apoly Attribute.
        * @return apoly Attribute
        */
        
        public org.ivoa.dm.adqlgeom.Polygon getApoly() {
        return (org.ivoa.dm.adqlgeom.Polygon)this.apoly;
        }
        
        
        /**
        * Set apoly Attribute.
        * @param pApoly value to set
        */
        public void setApoly(final org.ivoa.dm.adqlgeom.Polygon pApoly) {
        
        this.apoly = pApoly;
        }
        
        /**
        * fluent setter for apoly Attribute.
        * @param pApoly value to set
        * @return ATest
        */
        public net.ivoa.dm.adqlgeom.test.ATest withApoly(final org.ivoa.dm.adqlgeom.Polygon pApoly) {
        setApoly(pApoly);
        return this;
        }

    
        /**
        * Returns aninterval Attribute.
        * @return aninterval Attribute
        */
        
        public org.ivoa.dm.adqlgeom.Interval getAninterval() {
        return (org.ivoa.dm.adqlgeom.Interval)this.aninterval;
        }
        
        
        /**
        * Set aninterval Attribute.
        * @param pAninterval value to set
        */
        public void setAninterval(final org.ivoa.dm.adqlgeom.Interval pAninterval) {
        
        this.aninterval = pAninterval;
        }
        
        /**
        * fluent setter for aninterval Attribute.
        * @param pAninterval value to set
        * @return ATest
        */
        public net.ivoa.dm.adqlgeom.test.ATest withAninterval(final org.ivoa.dm.adqlgeom.Interval pAninterval) {
        setAninterval(pAninterval);
        return this;
        }

    

        /**
          A builder class for ATest, mainly for use in the functional builder pattern.
        */
        public static class ATestBuilder {
           


                   /**
                   * .
                   */
                   public org.javastro.ivoacore.pgsphere.types.Point apoint;
                           


                   /**
                   * .
                   */
                   public org.ivoa.dm.adqlgeom.Circle acircle;
                           


                   /**
                   * .
                   */
                   public org.ivoa.dm.adqlgeom.Polygon apoly;
                           


                   /**
                   * .
                   */
                   public org.ivoa.dm.adqlgeom.Interval aninterval;
                           

           private ATestBuilder with (java.util.function.Consumer <ATestBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a ATest from this builder.
           *  @return an object initialized from the builder.
           */
           public ATest create()
           {
             return new ATest (
          
              apoint,acircle,apoly,aninterval
              );
           }
         }
        /**
        *   create a ATest in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static ATest createATest (java.util.function.Consumer <ATestBuilder> f)
         {
             return new ATestBuilder().with(f).create();
         }
    

    @Override
    public void forceLoad() {
    
    }
    
    /**
      * {@inheritDoc}
      */
      @Override
      public void delete(jakarta.persistence.EntityManager em) {
      
              em.remove(this); // nothing special to do
          

      }
      
}
  